"""30 roles

Revision ID: 025f1f155ba6
Revises: 4c1de608e227
Create Date: 2023-06-24 09:32:57.803605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025f1f155ba6'
down_revision = '4c1de608e227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
