"""5 Updated tables foreign keys

Revision ID: 0aab2f8ee8c2
Revises: a9e8213d5368
Create Date: 2023-06-13 18:19:14.625958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aab2f8ee8c2'
down_revision = 'a9e8213d5368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('creditcards', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'creditcards', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creditcards', type_='foreignkey')
    op.drop_column('creditcards', 'account_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'client_id')
    # ### end Alembic commands ###
