"""22 Updated tables

Revision ID: 29d340bf7c29
Revises: 832227ceacf3
Create Date: 2023-06-15 13:18:20.108885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d340bf7c29'
down_revision = '832227ceacf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('se', sa.String(length=6), nullable=False))
    op.drop_column('clients', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sex', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_column('clients', 'se')
    # ### end Alembic commands ###
