"""3 Updated tables

Revision ID: 2d87d4091e93
Revises: f0e158eede10
Create Date: 2023-06-13 17:17:13.555245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87d4091e93'
down_revision = 'f0e158eede10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
