"""19 Updated tables

Revision ID: 3cffefa4048b
Revises: a7c27163191f
Create Date: 2023-06-15 11:28:22.616497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cffefa4048b'
down_revision = 'a7c27163191f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
