"""26 Updated tables (tax_numbers)

Revision ID: 3e54671eb9a2
Revises: 770fd6c73be0
Create Date: 2023-06-19 18:34:39.617733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e54671eb9a2'
down_revision = '770fd6c73be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tax_number', sa.BigInteger(), nullable=False))
    op.add_column('clients', sa.Column('trusted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['tax_number'])
    op.drop_column('clients', 'truseted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('truseted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'trusted')
    op.drop_column('clients', 'tax_number')
    # ### end Alembic commands ###
