"""29 City column

Revision ID: 4c1de608e227
Revises: 7013fa71dae8
Create Date: 2023-06-24 09:29:03.340939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1de608e227'
down_revision = '7013fa71dae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('city', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'city')
    # ### end Alembic commands ###
