"""15 Updated tables

Revision ID: 661a78d40435
Revises: ef1969721157
Create Date: 2023-06-15 09:57:38.054703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661a78d40435'
down_revision = 'ef1969721157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_numb', sa.String(length=50), nullable=False))
    op.drop_column('accounts', 'account_number')
    op.add_column('creditcards', sa.Column('card_numb', sa.BigInteger(), nullable=False))
    op.drop_column('creditcards', 'card_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditcards', sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('creditcards', 'card_numb')
    op.add_column('accounts', sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'account_numb')
    # ### end Alembic commands ###
