"""27 Account statu

Revision ID: 683246421fea
Revises: 3e54671eb9a2
Create Date: 2023-06-21 18:14:21.862950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683246421fea'
down_revision = '3e54671eb9a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'active')
    # ### end Alembic commands ###
