"""24 Updated tables

Revision ID: 770fd6c73be0
Revises: d507e81fc094
Create Date: 2023-06-15 17:55:53.787955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770fd6c73be0'
down_revision = 'd507e81fc094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    op.drop_table('clientm2mbank')
    op.add_column('clients', sa.Column('vip', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('truseted', sa.Boolean(), nullable=True))
    op.add_column('creditcards', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creditcards', 'activated')
    op.drop_column('clients', 'truseted')
    op.drop_column('clients', 'active')
    op.drop_column('clients', 'vip')
    op.create_table('clientm2mbank',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='clientm2mbank_bank_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='clientm2mbank_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='clientm2mbank_pkey')
    )
    op.create_table('banks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bank_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='banks_pkey')
    )
    # ### end Alembic commands ###
