"""16 Updated tables

Revision ID: 7b0d39ab5efe
Revises: 661a78d40435
Create Date: 2023-06-15 09:59:40.229792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0d39ab5efe'
down_revision = '661a78d40435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=50), nullable=False))
    op.drop_column('accounts', 'account_numb')
    op.add_column('creditcards', sa.Column('card_number', sa.BigInteger(), nullable=False))
    op.drop_column('creditcards', 'card_numb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditcards', sa.Column('card_numb', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('creditcards', 'card_number')
    op.add_column('accounts', sa.Column('account_numb', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
