"""33 Managers confirmed

Revision ID: 80fedfb7512c
Revises: 7126f60c0fec
Create Date: 2023-06-24 12:25:13.953897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fedfb7512c'
down_revision = '7126f60c0fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'confirmed')
    # ### end Alembic commands ###
