"""21 Updated tables

Revision ID: 832227ceacf3
Revises: c6962513150c
Create Date: 2023-06-15 11:29:40.901476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832227ceacf3'
down_revision = 'c6962513150c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sex', sa.String(length=5), nullable=False))
    op.drop_column('clients', 'se')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('se', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'sex')
    # ### end Alembic commands ###
