"""11 Updated tables

Revision ID: 8792e4f91f5d
Revises: fce68dc77f6a
Create Date: 2023-06-15 09:40:29.954091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8792e4f91f5d'
down_revision = 'fce68dc77f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=50), nullable=False))
    op.drop_column('accounts', 'account_numb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_numb', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
