"""12 Updated tables

Revision ID: a0d712db0ca7
Revises: 8792e4f91f5d
Create Date: 2023-06-15 09:49:57.224904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d712db0ca7'
down_revision = '8792e4f91f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
