"""9 Updated tables

Revision ID: a61e0a534180
Revises: ebda473a1405
Create Date: 2023-06-15 09:38:08.593150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61e0a534180'
down_revision = 'ebda473a1405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
