"""18 Updated tables

Revision ID: a7c27163191f
Revises: 095d6d38512b
Create Date: 2023-06-15 11:23:21.450831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c27163191f'
down_revision = '095d6d38512b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sex', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'sex')
    # ### end Alembic commands ###
