"""4 Updated tables

Revision ID: a9e8213d5368
Revises: 2d87d4091e93
Create Date: 2023-06-13 18:16:30.043419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e8213d5368'
down_revision = '2d87d4091e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
