"""20 Updated tables

Revision ID: c6962513150c
Revises: 3cffefa4048b
Create Date: 2023-06-15 11:28:55.098155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6962513150c'
down_revision = '3cffefa4048b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('se', sa.String(), nullable=False))
    op.drop_column('clients', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'se')
    # ### end Alembic commands ###
