"""13 Updated tables

Revision ID: d3afc4869d38
Revises: a0d712db0ca7
Create Date: 2023-06-15 09:50:31.309360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3afc4869d38'
down_revision = 'a0d712db0ca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
