"""23 Updated tables

Revision ID: d507e81fc094
Revises: 29d340bf7c29
Create Date: 2023-06-15 13:18:46.675298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd507e81fc094'
down_revision = '29d340bf7c29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sex', sa.String(length=6), nullable=False))
    op.drop_column('clients', 'se')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('se', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('clients', 'sex')
    # ### end Alembic commands ###
