"""8 Updated tables

Revision ID: ebda473a1405
Revises: 23e773f03fb1
Create Date: 2023-06-15 09:30:57.947169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebda473a1405'
down_revision = '23e773f03fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
