"""14 Updated tables

Revision ID: ef1969721157
Revises: d3afc4869d38
Create Date: 2023-06-15 09:50:50.193820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1969721157'
down_revision = 'd3afc4869d38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
