"""2 Updated tables

Revision ID: f0e158eede10
Revises: beb2f59bd99f
Create Date: 2023-06-13 16:56:21.051499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e158eede10'
down_revision = 'beb2f59bd99f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks_m2m_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('current_deposit', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('bank_code', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('secret_word', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('passport_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'clients', ['passport_number'])
    op.create_unique_constraint(None, 'clients', ['email'])
    op.create_unique_constraint(None, 'clients', ['phone'])
    op.add_column('creditcards', sa.Column('pin_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creditcards', 'pin_code')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'passport_number')
    op.drop_column('clients', 'secret_word')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'email')
    op.drop_column('banks', 'bank_code')
    op.drop_column('accounts', 'current_deposit')
    op.drop_table('banks_m2m_clients')
    # ### end Alembic commands ###
