"""10 Updated tables

Revision ID: fce68dc77f6a
Revises: a61e0a534180
Create Date: 2023-06-15 09:39:37.553812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce68dc77f6a'
down_revision = 'a61e0a534180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_numb', sa.String(length=50), nullable=False))
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'account_numb')
    # ### end Alembic commands ###
